version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinic_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  # PHP Service (Laravel)
  php:
    build: ./docker/php
    container_name: php_container
    restart: always
    volumes:
      - ./IdentifyService:/var/www/identify-service
      - ./ReservationService:/var/www/reservation-service
    depends_on:
      - mysql

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./IdentifyService:/var/www/identify-service
      - ./ReservationService:/var/www/reservation-service
    depends_on:
      - php


  frontend:
    build:
      context: ./frontend/pediatricka_ambulancia
    volumes:
      - ./frontend/pediatricka_ambulancia:/app
      - /app/node_modules 
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - nginx


volumes:
  mysql_data:
